name: flutter_base
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
#  sdk: ">=2.12.0 <3.0.0"

flutter_intl:
  enabled: true

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #Domain & Data layer dependencies
  domain:
    path: domain
  data:
    path: data
  flutter_riverpod: ^0.12.2
  dartz: ^0.9.2
  rxdart: ^0.25.0
  fluttertoast: ^7.1.6
  responsive_builder: ^0.2.0+2
  flutter_svg:
  responsive_framework: ^0.0.14
  intl: 0.17.0
  animated_theme_switcher: ^1.0.5
  package_info: ^2.0.0
  cached_network_image: ^2.0.0
  drag_and_drop_lists: ^0.3.2
  carousel_slider: ^2.3.1
  flutter_inappwebview: ^5.3.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - asset/svg/

  fonts:
    - family: Montserrat
      fonts:
        - asset: asset/font/Montserrat-Thin.ttf
          weight: 100
        - asset: asset/font/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: asset/font/Montserrat-Light.ttf
          weight: 300
        - asset: asset/font/Montserrat-Regular.ttf
          weight: 400
        - asset: asset/font/Montserrat-Medium.ttf
          weight: 500
        - asset: asset/font/Montserrat-SemiBold.ttf
          weight: 600
        - asset: asset/font/Montserrat-Bold.ttf