enum ErrorType {
  //custom error
  IOEXCEPTION,
  NO_BIO_METRIC_SUPPORT,

  //Network Error
  NETWORK,
  NET_SERVER_MESSAGE,
  NET_NO_INTERNET_CONNECTION,
  NET_WRONG_VERIFICATION_CODE,
  NET_ACCOUNT_ALREADY_EXIST,
  NET_ACCOUNT_NOT_VERIFIED,
  NET_INVALID_CREDENTIAL,
  NET_OTP_EXPIRED,

  // UI Errors
  UI,
  EMPTY_EMAIL,
  EMPTY_PHONE,
  INVALID_EMAIL,
  INVALID_PHONE,
  EMPTY_PASSWORD,
  PASSWORD_NOT_MATCHED,
  EMPTY_FIRST_NAME,
  EMPTY_DOB,
  EMPTY_DATE,
  EMPTY_CURRENCY,
  EMPTY_MOVIE_TYPE,

  //DB ERROR
  DATABASE,
  DATABASE_NOT_SUPPORTED,
  DB_ERROR1,
  DB_USER_NOT_FOUND,
}
